### ISSUE TITLE
support different completion backends

### ISSUE THREAD

**Issue by thomp** [dtk01/dtk#5]
Per @yiufung's suggestion, support different completion backends.  Consider providing customized option such as `dtk-completing-read-function`. The symbol would point to the desired completion backend (e.g., ivy-completing-read, helm-completing-read, ...).

**Comment by yiufung** [comment]
I planned to work on this, but a second thought come by: if user already enable `ivy-mode` or `helm-mode`, `completing-read` is automatically redirected to these reading functions, so the option becomes not necessary. It's not an urgent option, so I'd work on other features first.

**Comment by dtk01** [comment]
Agreed - this seems a relatively minor issue.

**Comment by thomp** [comment]
As `completing-read` is redirected with most completion frameworks, this issue can be put on the back burner for the time being.
